
modLoader="javafml" #mandatory

loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="fieryfoes" #mandatory

version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Fiery Foes" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Love, Cheese and small house plants" #optional

description='''
My bro's Mod
'''

[[dependencies.fieryfoes]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[44,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.fieryfoes]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
